steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/internal-apis', '-t', 'gcr.io/$PROJECT_ID/internal-apis:current', '.']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s-deployment.yml']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s-service.yml']

# my-image is pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/internal-apis'