steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/internal-apis', '-t', 'gcr.io/$PROJECT_ID/internal-apis:current', '.']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s-deployment.yml', '--namespace=elixir']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lti-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s-service.yml', '--namespace=elixir']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lti-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args: [
            '-c',
            'kubectl patch deployment internal-apis --namespace=elixir -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +''%s''`\"}}}}}"'
          ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lti-cluster'

# my-image is pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/internal-apis'
