apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-apis
  labels:
    app: internal-apis
    tier: backend
spec:
  template:
    metadata:
      name: internal-apis
      labels:
        app: internal-apis
        tier: backend
    spec:
      containers:
      - name: internal-apis
        image: k3pocregistry.azurecr.io/sdp_apis:current
        imagePullPolicy: "Always"
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      tier: backend
      app: internal-apis