apiVersion: v1
kind: Service
metadata:
  name: internal-apis
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: internal-apis
    tier: backend
  ports:
    - port: 8080
      targetPort: 4000
  type: LoadBalancer