apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-apis
  labels:
    app: internal-apis
    tier: backend
spec:
  template:
    metadata:
      name: internal-apis
      labels:
        app: internal-apis
        tier: backend
    spec:
      containers:
      - name: internal-apis
        image: gcr.io/data-warehouse-project-235018/internal-apis:current
  replicas: 3
  selector:
    matchLabels:
      tier: backend
      app: internal-apis