apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-apis
  labels:
    app: internal-apis
    tier: backend
spec:
  template:
    metadata:
      name: internal-apis
      labels:
        app: internal-apis
        tier: backend
    spec:
      containers:
      - name: internal-apis
        image: gcr.io/data-warehouse-project-235018/internal-apis:current
        imagePullPolicy: "Always"
        env:
          - name: "KAFKA_EX_HOST"
            value: "34.69.58.165"
          - name: "KAFKA_EX_PORT"
            value: "9094"
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      tier: backend
      app: internal-apis