apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-apis
  labels:
    app: internal-apis
    type: back-end
spec:
  template:
    metadata:
      name: internal-apis
      labels:
        app: internal-apis
        type: back-end
    spec:
      containers:
      - name: internal-apis
        image: gcr.io/data-warehouse-project-235018/internal-apis:latest
  replicas: 3
  selector:
    matchLabels:
      type: back-end